### PR TITLE
HAWKULAR-998 - Added an optional filter to convert GET parameters to auth data

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
@tsegismont , could you please review and test? For usage instructions, refer to the changes to the sample module, but basically, you should just include the dependency on org.hawkular.accounts:hawkular-accounts-request-parameter-auth-filter

**Comment by tsegismont** [comment]
The code looks fine to me. But we can't configure the parameter names, correct? This makes me wonder if we shouldn't simply add your code to Metrics, with hardcoded parameters names for Influx. Or do you think this handler could be used in other projects?

**Comment by jpkrohling** [comment]
This is mostly for your component to consume. I actually added a comment on the code that we should make the parameters configurable, but if you only send one parameter name for username and one for password, I can adjust it for your needs.

If/when we have another component with similar needs, I can refactor it to handle configurable parameters.

**Comment by tsegismont** [comment]
As agreed with @jpkrohling , we will move this code to Metrics. There is little chance that another module will need such a hack, so we'd like to avoid to maintain a common module.

**Pull request closed without merging**
