### PR TITLE
HAWKULAR-180 - Disabled sub organizations.

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
@ppalaga , could you review this one?

**Comment by ppalaga** [comment]
@jpkrohling should I review in spite of the CI failure?

**Comment by jpkrohling** [comment]
It seems I broke a test :D Good thing that they are there. I'll fix it and let you know once it's ready for review.

**Comment by jpkrohling** [comment]
False positive...

**Comment by ppalaga** [comment]
Although, the change looks quite obvious and correct (as far as I can understand), was there no mention of suborgs in docs? And no testcase for that? Otherwise, I'd be ready to merge if I had the permission :)

**Comment by jpkrohling** [comment]
Right now, there are no test for the REST endpoints, but you are right about the docs.

**Comment by jpkrohling** [comment]
Added a couple of notes about this to the documentation (javadoc and readme).

**Comment by ppalaga** [comment]
LGTM

**Comment by jpkrohling** [comment]
Merged via CLI.

**Pull request closed without merging**
