### PR TITLE
Make the integration tests run and pass again with c* 3.3

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jpkrohling could you please review and eventually merge?

**Comment by ppalaga** [comment]
retest this please

**Comment by ppalaga** [comment]
@jpkrohling any idea why Jenkins is failing?

**Comment by jpkrohling** [comment]
Yes, let me see if I can fix it.

**Comment by jpkrohling** [comment]
For reference: 
https://bugzilla.redhat.com/show_bug.cgi?id=1287638
https://bugzilla.redhat.com/show_bug.cgi?id=1287780

**Comment by jpkrohling** [comment]
retest this please

**Comment by jpkrohling** [comment]
retest this please

**Comment by jpkrohling** [comment]
retest this please

**Comment by ppalaga** [comment]
@jpkrohling passing now

**Pull request merged**
