### PR TITLE
HAWKULAR-761 Move Hawkular onto WF 10

### PR DESCRIPTION
**Pull request by ppalaga**
[Don't merge yet] - depends on hawkular-parent 26 that needs to be released yet

### CODE REVIEW

**Comment by ppalaga** [comment]
9190101 bring the newest round of my attempts to produce Accounts on top of WildFly 10. Note that 9190101 depends on https://github.com/ppalaga/hawkular-parent-pom/commit/dcf7fbc62d41bd8b79257fa276008c9adf5abbf1 

Anyway, still no success here. It fails in smoke test:

```
java.lang.RuntimeException: JBAS011137: Cannot load module org.jboss.as.embedded from: local module loader @6c130c45 (finder: local module finder @50ad3bc1 (roots: /home/ppalaga/git/hawkular-accounts/integration-tests/smoke/target/hawkular-accounts-distribution-1.1.2.Final-SNAPSHOT/modules,/home/ppalaga/git/hawkular-accounts/integration-tests/smoke/target/hawkular-accounts-distribution-1.1.2.Final-SNAPSHOT/modules/system/layers/base))
...
```

Esp. the last commit "Upgrade to arquillian-bom 1.1.9.Final and wildfly-arquillian-container-embedded 8.2.1.Final" does not seem to bring any improvement.

I am giving up as @jpkrohling can take this over today.

**Comment by ppalaga** [comment]
https://github.com/hawkular/hawkular-parent-pom/commit/2f02cdc205224853ec0b9311d310363679663d76 fixes the issue with existing non-empty directory when building a srcdep

**Comment by jpkrohling** [comment]
This should _not_ yet be merged. The Keycloak branch used is outdated and needs to be synchronized with KC master. One side effect that I've seen is about the Freemarker version, but there might be other ones.

**Comment by jpkrohling** [comment]
It seems that their current master is WF-10-Ready. The tests passes when running the following with my branch jpk-HAWKULAR-761 (which was made on top of yours)

```
mvn clean install -Pitest -Dversion.org.keycloak=1.7.0.Final-SRC-revision-f6d716a3866a4dd5655b1d9cc76c7bd8b5d8a2e3
```

**Comment by ppalaga** [comment]
The latest iteration b0279f0 is ready to be merged from my point of view. @jpkrohling could you please review and eventually merge?

**Comment by jpkrohling** [comment]
Rebased branch here: https://github.com/jpkrohling/hawkular-accounts/tree/jpk-HAWKULAR-761

**Comment by jpkrohling** [comment]
Squashed branch: https://github.com/jpkrohling/hawkular-accounts/tree/jpk-HAWKULAR-761-squashed

**Comment by ppalaga** [comment]
5810985 is a result of rebase on top of the current master. @jpkrohling please merge.

**Comment by jpkrohling** [comment]
This is being replaced by #74 .

**Pull request closed without merging**
