### PR TITLE
Get rid of the feature-pack-resources and the module.xml definition.

### PR DESCRIPTION
**Pull request by metlos**
This can be simplified into a single module with the feature-pack-plugin
1.1.2 and newer (which we're now using).

This is a prep step for another PR that I will be sending once nest is updated with new datasource definitions.

### CODE REVIEW

**Comment by jpkrohling** [comment]
Can one of the admins verify this patch?

**Comment by jpkrohling** [comment]
add to whitelist

**Comment by jpkrohling** [comment]
@ppalaga , I think you are the right one for reviewing this :)

**Comment by ppalaga** [comment]
@metlos thanks for the effort to make things cleaner. I can confirm, that your solution works properly. 

However, it brings one important disadvantage: the resulting xml fragments are not a part of any jar deployed to a maven repo (note that the `feature-pack` module has packaging `pom`). It will thus be impossible to enhance them in the downstream (e.g. using XSL). Although we do not do any such enhancement ATM, I vote for keeping the possibility open. 

This being said, I see several options that could be looked at:

(a) change the packaging of feature-pack to `jar` - not sure at all what it can break

(b) keep feature-pack-resources as is, just remove the module.xml and somehow bring the fragments to feature-pack (dependency-plugin?)

(c) do nothing

**Comment by metlos** [comment]
@ppalaga while the XSL fragments do not end up there, the resulting XMLs do, which I think is enough for usability of the feature packs? Or do you envision a scenario where one would like to "update the default subsystem in a similar way to how this other feature pack does, only slightly differently" and use XSL to update the XSL of the other feature pack?

**Comment by metlos** [comment]
IMHO the same can be achieved by having XSL update the resulting XMLs of the subsystems defined by the "other feature pack".

**Comment by ppalaga** [comment]
> while the XSL fragments do not end up there, the resulting XMLs do

@metlos not sure if understand you correctly. 
My position is: 

(1) whether the XSL files [1] end up in a jar or zip does not matter

(2) I want the XML fragments that are the result of the XSL transformations [1] to be included in some jar or zip - i.e. want to see hawkular-accounts-ejb3.xml, hawkular-accounts-messaging-activemq.xml and
hawkular-accounts-security.xml in some jar or zip, so that they can be further processed in the downstream.

If you mean that (2) is the case, please tell me which jar/zip are they part of?

[1] https://github.com/hawkular/hawkular-accounts/tree/2.0.18.Final/feature-pack-resources/src/main/xsl/subsystem-templates

**Comment by ppalaga** [comment]
@metlos OK, forget my rant. I am sorry about it. I have built your branch again and the files are really there in `subsystem-templates` directory of the zip. Hence I am OK with this PR, once you rebase on top of master.

**Comment by metlos** [comment]
rebased, waiting on travis...

**Pull request merged**
