### PR TITLE
HAWKULAR-860 Update CSS to behave like patternfly on mobile

### PR DESCRIPTION
**Pull request by cardosogabriel**

### CODE REVIEW

**Comment by jpkrohling** [comment]
Can one of the admins verify this patch?

**Comment by jpkrohling** [comment]
Add to whitelist

**Comment by jpkrohling** [comment]
Merged via CLI

**Comment by ppalaga** [comment]
> Add to whitelist

Looks like @jpkrohling is speaking their secret language with his Jenkins ;)

Juca, I just noticed you are away today. May I release?

**Comment by jpkrohling** [comment]
Sure, be my guest :)

**Pull request closed without merging**
