### PR TITLE
hawkular-parent 33 and related fixes

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jpkrohling could you please review and eventually merge?

Not sure why it fails on your Jenkins it passed here.

**Comment by jpkrohling** [comment]
Please retest this

**Comment by jpkrohling** [comment]
Probably some connection issue between the master and slave. The comment above should trigger a retest

**Comment by ppalaga** [comment]
Does the order of the words matter? This page says "retest this please" rather than "please retest this" https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin

**Comment by jpkrohling** [comment]
retest this please

**Comment by jpkrohling** [comment]
It seems it matters :)

**Comment by jpkrohling** [comment]
retest this please

**Comment by jpkrohling** [comment]
retest this please

**Comment by jpkrohling** [comment]
Problems with the reliable Jenkins server, so, merging it manually :)

**Pull request merged**
