### PR TITLE
@JsonIgnore getIdAsUUID()

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jpkrohling could you please review and eventually merge?

This seems to be necessary to be able to deserialize Accunts entities, such as `HawkularUser`, etc.

**Comment by jpkrohling** [comment]
I have nothing against this, but I'm missing a context here. Why/where is this needed?

**Comment by jpkrohling** [comment]
Usually, when you can control the ObjectMapper that is used to serialize/deserialize the entities, you could use this:

```
 mapper.configure(DeserializationConfig.Feature.FAIL_ON_UNKNOWN_PROPERTIES, false);
```

In other cases, like in REST endpoints, I usually make a "RestEntity", which are simple strings. This way, I can ensure that objects are properly created based on actual input values.

**Comment by ppalaga** [comment]
> context here. Why/where is this needed?

I am migrating the e2e test in HK main from Groovy to Java.

**Pull request merged**
