### PR TITLE
HAWKULAR-505 - Added API for Web Sockets authentication

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
@ppalaga , would you mind reviewing this one?

**Comment by ppalaga** [comment]
@jpkrohling end of first review round

**Comment by jpkrohling** [comment]
Added a couple of commits, that should fix most of the items. The only open item is about the NPE and PrintWriter. If you agree with me there, I'll then squash and merge.

**Comment by ppalaga** [comment]
> The only open item is about the NPE and PrintWriter. If you agree with me there, I'll then squash and merge.

You say that NPE really happens sometimes? Thinking about it again, should it not be the responsibility of the CDI container to know in which order it should inject and invoke the classes? In case it is not working properly, perhaps the CDI container does not have enough information and we should somehow declare the implicit dependencies explicitly? I do not feel very strong in this area. Therefore, feel free to ignore me, but if you say that the NPE really happens sometimes, the problem needs a solution and you should perhaps consider consulting with somebody more experienced.

With `PrintWriter`, my position is that relying on platform's default is wrong. The `PrintWriter` should be creates using some 8-bit ASCII-compatible encoding like UTF-8, ISO Latin1, or similar.

**Comment by jpkrohling** [comment]
About the NPE, it should never happen if the consumer is properly set. It will only happen if the consumer forgets, for instance, to add the servlet context listener that creates the `@ApplicationScoped` bean that produces the context. So, a `NullPointerException` is what we want: an exception saying that we don't expect this reference to be null. CDI takes care of that nicely, but if nothing has populated the `ApplicationScoped`, then there's nothing CDI can do about it.

**Pull request merged**
