### PR TITLE
Updated to Keycloak RC1

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by jpkrohling** [comment]
Once @theute reviews/approves, I'll merge it via CLI.

**Comment by theute** [comment]
Some comments after a quick look (and BUILD SUCCESS on my machine), note that some are unrelated to this commit though:
- distribution -> dist (as discussed on IRC)
- wildfly version property is already defined in hawkular pom parent, ${version.org.wildfly}
- <version.keycloak> should be <version.org.keycloak> (org id)

**Comment by jpkrohling** [comment]
@theute , would it be OK to open a JIRA that would fix those points? Or should it be worked for this PR? Also, not sure what you mean in your last point: " should be (org id)".

**Comment by theute** [comment]
I don't think any of the points are blocker/regression so that could still be merged.
I am not sure about the impact on kettle though.
" should be (org id)" is a github format problem, it was on the same line as the 2nd "bullet", for ${version.wildfly} issue the correct format is ${version._orgid_}

**Comment by jpkrohling** [comment]
There should be no or minimal impact on kettle, as far as accounts is concerned, as the "distribution" module is totally independent from it. About the versions: got it. 

Created HAWKULAR-204 for fixing those points. I'll merge it via CLI then. Thanks for the review!

**Pull request closed without merging**
