### PR TITLE
HAWKULAR-881 - Added 'Join Organization' feature.

### PR DESCRIPTION
**Pull request by jpkrohling**

### CODE REVIEW

**Comment by ppalaga** [comment]
@jpkrohling the first round of review finished. I definitely do not have the time to check the coverage of the tests, sorry.

**Comment by jpkrohling** [comment]
I think all the changes were made in the follow up commit. Once this PR is good, I'll squash the commits and merge.

**Comment by ppalaga** [comment]
@jpkrohling the second round of review finished.

**Comment by jpkrohling** [comment]
Commit for the second round done!

**Comment by ppalaga** [comment]
OK, except for the tests coverage that I have no time for, looks good.

**Pull request merged**
